all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: 34.220.157.187
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/aws
        server-two:
          ansible_host: 52.12.203.232
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/aws
